package frontend.corba;


/**
* corba/frontendPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Saturday, November 21, 2020 10:14:01 o'clock PM EST
*/

public abstract class frontendPOA extends org.omg.PortableServer.Servant
 implements frontendOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseItem", new java.lang.Integer (3));
    _methods.put ("findItem", new java.lang.Integer (4));
    _methods.put ("returnItem", new java.lang.Integer (5));
    _methods.put ("exchangeItem", new java.lang.Integer (6));
    _methods.put ("addCustomerWaitList", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/frontend/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         int price = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity, price);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba/frontend/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // corba/frontend/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // corba/frontend/purchaseItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         String $result = null;
         $result = this.purchaseItem (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // corba/frontend/findItem
       {
         String customerID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (customerID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // corba/frontend/returnItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfReturn = in.read_string ();
         String $result = null;
         $result = this.returnItem (customerID, itemID, dateOfReturn);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // corba/frontend/exchangeItem
       {
         String customerId = in.read_string ();
         String newItemId = in.read_string ();
         String oldItemId = in.read_string ();
         String dateOfExchange = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (customerId, newItemId, oldItemId, dateOfExchange);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // corba/frontend/addCustomerWaitList
       {
         String itemID = in.read_string ();
         String customerID = in.read_string ();
         String $result = null;
         $result = this.addCustomerWaitList (itemID, customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // corba/frontend/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/frontend:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public frontend _this() 
  {
    return frontendHelper.narrow(
    super._this_object());
  }

  public frontend _this(org.omg.CORBA.ORB orb) 
  {
    return frontendHelper.narrow(
    super._this_object(orb));
  }


} // class frontendPOA
