package frontend.corba;


/**
* corba/frontendOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Tuesday, November 24, 2020 9:17:50 o'clock AM EST
*/

public interface frontendOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity, int price);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String exchangeItem (String customerId, String newItemId, String oldItemId, String dateOfExchange);
  String addCustomerWaitList (String itemID, String customerID);
  void shutdown ();
} // interface frontendOperations
