package frontend.corba;

/**
* corba/frontendHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Saturday, November 21, 2020 10:14:01 o'clock PM EST
*/

public final class frontendHolder implements org.omg.CORBA.portable.Streamable
{
  public frontend value = null;

  public frontendHolder ()
  {
  }

  public frontendHolder (frontend initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = frontendHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    frontendHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return frontendHelper.type ();
  }

}
