package frontend.corba;


/**
* corba/frontend.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Saturday, November 21, 2020 10:14:01 o'clock PM EST
*/

public interface frontend extends frontendOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontend
