package frontend.corba;


/**
* corba/frontendHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Saturday, November 21, 2020 10:14:01 o'clock PM EST
*/

abstract public class frontendHelper
{
  private static String  _id = "IDL:corba/frontend:1.0";

  public static void insert (org.omg.CORBA.Any a, frontend that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static frontend extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (frontendHelper.id (), "frontend");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static frontend read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_frontendStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, frontend value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static frontend narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontend)
      return (frontend)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _frontendStub stub = new _frontendStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static frontend unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontend)
      return (frontend)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _frontendStub stub = new _frontendStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
