package frontend.corba;


/**
* corba/frontend.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend-idl.idl
* Tuesday, November 24, 2020 9:17:50 o'clock AM EST
*/

public interface frontend extends frontendOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontend
